name: ultron_5
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_map: ^0.14.0
  flutter_mapbox_navigation: ^0.0.26
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.10
  firebase_storage: ^10.2.9
  image_picker: ^0.8.4+11
  firebase_core: ^1.13.1
  dio: ^4.0.4
  mapbox_gl: ^0.15.0
  shared_preferences: ^2.0.13
  flutter_dotenv: ^5.0.2
  google_fonts: ^2.3.1
  flutter_rating_bar: ^4.0.0
  location: ^4.3.0
  url_launcher: ^6.0.20
  carousel_slider: ^4.0.0
  speech_to_text: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/config/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
